
## Pay attention to the formatting, newlines, and ### delimiting- specifically for INSTRUCT models
INITIAL_PROMPT_TMPL = (
    """### Instruction:  

    Given the context below, attempt to answer the following query: "{question}"     

    If no answer exists in the given context, respond with: "No answer given"
    
    Context: {context_str}

    ### Response:

    """
)

# INITIAL_PROMPT_TMPL = (
#     """### Instruction:  

#      Given the context below, attempt to answer the following query: "{question}"     

#      Rules for your response:
#         - If the query cannot be answered using the context below, your response should be ONLY: "No answer given"     
#         - If the query can be answeed using the context below, you should append the source to the response.
#         - Your response should NOT contain the original query.

#      Context: {context_str}
     
#      Examples:
     
#      Query: "Summarize the meeting that took place on April 23rd"     
#      Response: "The meeting was about an iOS app that grants the user x-ray vision.  (Source: '/docs/meeting-minutes-4-23-2023.pdf')"

#      Query: "Tell me about product ABC"
#      Response: "No answer given"

#     ### Response:

#     """
# )

A_CONSOLIDATE_ANSWERS_PROMPT_TMPL = (
    """### Instruction:

    Given the question: "{question}"
    
    Provide a single consolidated answer to the question by considering the following list of completions generated by another AI. 
    The final answer should be concise, to the point, and take into account any relevant data presented in the completions.         
    Ensure that the final answer does not contain duplicate or extraneous information that does not contribute to the consolidated answer.    
    After printing the final answer, print a list of the sources used by the provided completions that were used to make the final answer.
    
    Other Completions:
    \n\t- {answers}        

    ### Response:

     """
)

CONSOLIDATE_ANSWERS_PROMPT_TMPL = (
    """### Instruction:

    Given the question: "{question}"
    
    Provide a single consolidated answer to the question by considering the following list of answers generated by another AI. 

    The final answer should be concise, to the point, and take into account any relevant data presented in the other answers.         
    Ensure that the final answer does not contain duplicate or extraneous information that does not contribute to the consolidated answer.    
    When responding with the final answer, append a bulleted list of the sources associated with the other answers that contributed to the final answer.
    
    Other Asnwers:
    \n\t- {answers}        

    ### Response:

     """
)

PRE_PROCESS_QUERY_PROMPT_TMPL = (
    """### Instruction:

    Given the search term "{question}", 
    please organize the search terms in order of priority, providing a comma-delimited list.

    Example search term and response:

    Search term: Please tell me which meetings Mr. Jack Smith participated in durring 2022, and tell me what involvement he had.
    Response: Jack Smith, 2022, meetings, participated, involvement
    
    ### Response:

     """
)

## Old pre processing... this works, but it does not return items in priority order.  
# This is not that great. 
# If I want to optimize search results prior to using the llm, I should implement something better.
# PRE_PROCESS_QUERY_PROMPT_TMPL = (
#     """### Instruction:

#     Using the following statement, extract key search terms and answer with a comma separated list of those terms ONLY:  
    
#     "{question}"    

#     Remember that you should answer only with comma delimited values, for example:

#     "Value 1, value2, ValueThree, Etc."

#     ### Response:

#     """
# )